sub-scale=1.6
# include=mpv_linux.conf

# Languages #
alang=jpn,jp,eng,en,enUS,en-US,de,ger # Audio language priority
slang=eng,en,und,de,ger,jp,jap        # Subtitle language priority

save-position-on-quit=yes

