# include=mpv_linux.conf
sub-scale=1.6
audio-delay=-.2
force-window=yes
idle=once

# Languages #
alang=jpn,jp,eng,en,enUS,en-US,de,ger # Audio language priority
slang=eng,en,und,de,ger,jp,jap        # Subtitle language priority

save-position-on-quit=yes
save-watch-history=yes

# input-ipc-server=$HOME/.config/mpvc/mpvsocket0
input-ipc-server=/tmp/mpv.sock

